class Dimension:
    BOT_BAR_HEIGHT = 30
    TOP_BAR_HEIGHT = 30

    LEFT_MENU_MIN_WIDTH = 50
    LEFT_MENU_MAX_WIDTH = 160


class Color:
    LEFT_MENU_BG_COLOR = "#44475a"

    TOP_BOT_BAR_BG = "#21232d"
    TOP_BOT_BAR_TEXT = "#6272a4"

    CONTENT_BG = "#fbf8f4"
    LEFT_MENU_ACTIVE_BTN_COLOR = CONTENT_BG
